In [1]:
# In order to make this script working is necessary 
# to have installed the python packages listed below.
# In particular for awkde is possible to insall it with:

# git clone https://github.com/mennthor/awkde
# pip install [--user] [-e] ./awkde

# For more details please consult awkde github page at: https://github.com/mennthor/awkde

In [2]:
# Please notice: the dataset attached to this script consist only a subset of the entire dataset. 
# In particular, weekday 23 time slot.

#Also, on this dataset for the seek of brevity are already applied but not reported
# all the preprocessing steps including temporal and spatial one, in order to obtain data
# ready to be fitted by the model

In [3]:
import pandas as pd
import geopandas as gpd
import numpy as np
from sklearn.neighbors import KernelDensity
from sklearn.model_selection import GridSearchCV
from awkde import GaussianKDE
from copy import deepcopy
import pickle

In [4]:
dataset = pd.read_csv('Amsterdam_dataset_WD23.csv')

In [5]:
# eventhough also WGS84 coordinate system is available, UTM ones are preferred
# because it's the best choice to use default euclidean metric distance for GridSearchCV

In [6]:
kde_columns_utm_2d = ['start_longitude_utm', 'start_latitude_utm']
#start longitude and latitude are used for 2 dimensional KDE
#it's also possible to use end point(final destination)
# kde_columns_utm_2d = ['end_longitude_utm', 'end_latitude_utm']
kde_columns_utm_4d = ['start_longitude_utm', 'start_latitude_utm', 'end_longitude_utm', 'end_latitude_utm']
bandwidths_utm = np.geomspace(0.5, 10000, 100)

In [7]:
#optimal fixed bandwidth reaserarch in two dimensional space
for i in range(2):
    if i==0:
        grid_search_fixedKDE_2D =  GridSearchCV(KernelDensity(kernel='gaussian'),
                                    {'bandwidth': bandwidths_utm}, cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_2d].dropna())
        log_likelihood_results_fixedKDE_2D = pd.DataFrame(grid_search_fixedKDE_2D.cv_results_['params'])
        log_likelihood_results_fixedKDE_2D['mean_likelihood_score'] = grid_search_fixedKDE_2D.cv_results_['mean_test_score']
        best_bw = grid_search_fixedKDE_2D.best_params_['bandwidth']
    else:
        grid_search_fixedKDE_2D =  GridSearchCV(KernelDensity(kernel='gaussian'),
                                    {'bandwidth': np.linspace(best_bw/2, best_bw*1.5, 50)}, cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_2d].dropna())

In [8]:
grid_search_fixedKDE_2D.best_params_['bandwidth']

69.3198998416634

In [9]:
#it's now possible to fit a 2D fixed KDE with the optimal bandwidth
fixedKDE_2D = KernelDensity(kernel='gaussian',bandwidth=grid_search_fixedKDE_2D.best_params_['bandwidth']).fit(
    dataset[kde_columns_utm_2d])

In [10]:
#optimal fixed bandwidth reaserarch in four dimensional space
for i in range(2):
    if i==0:
        grid_search_fixedKDE_4D =  GridSearchCV(KernelDensity(kernel='gaussian'),
                                    {'bandwidth': bandwidths_utm}, cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_4d].dropna())
        log_likelihood_results_fixedKDE_4D = pd.DataFrame(grid_search_fixedKDE_4D.cv_results_['params'])
        log_likelihood_results_fixedKDE_4D['mean_likelihood_score'] = grid_search_fixedKDE_4D.cv_results_['mean_test_score']
        best_bw = grid_search_fixedKDE_4D.best_params_['bandwidth']
    else:
        grid_search_fixedKDE_4D =  GridSearchCV(KernelDensity(kernel='gaussian'),
                                    {'bandwidth': np.linspace(best_bw/2, best_bw*1.5, 50)}, cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_4d].dropna())

In [11]:
#it's now possible to fit a 4D fixed KDE with the optimal bandwidth
fixedKDE_4D = KernelDensity(kernel='gaussian',bandwidth=grid_search_fixedKDE_4D.best_params_['bandwidth']).fit(
    dataset[kde_columns_utm_4d])

In [12]:
######################################################################
#                  VARIABLE BANDWIDTH (ADAPTIVE) KDE                 #
######################################################################

In [13]:
# since the AwKDE package applies a transformation on the input data
# in order to return a sample space with zero mean vector an
# identity covariance matrix. As also the bandwidth has to be scaled
# therefore for the global_bw research we start from the optimal founded with
# scikit-learn library and divide it for the sample's average standard deviation in
#diffent dimensions.

In [14]:
average_std = np.sqrt(np.sum([np.power(dataset['start_longitude_utm'].std(),2),
                              np.power(dataset['start_latitude_utm'].std(),2)])/2)

In [15]:
global_bw_std = grid_search_fixedKDE_2D.best_params_['bandwidth']/average_std
global_bw_ranges = np.linspace(global_bw_std/2, global_bw_std*2, 100)

In [16]:
#it's possible to find the optimal global_bw with alpha=0.5 according 
# to silverman law

In [17]:
grid_search_2D_VKDE_alpha05 = GridSearchCV(GaussianKDE(diag_cov=False, alpha=0.5),
                                                        {'glob_bw': global_bw_ranges},
                                                      cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_2d].dropna())

In [18]:
VKDE_2D_alpha05 = GaussianKDE(alpha=0.5, 
                              glob_bw=grid_search_2D_VKDE_alpha05.best_params_['glob_bw'])
VKDE_2D_alpha05.fit(dataset[kde_columns_utm_2d])

(start_longitude_utm    121281.052258
 start_latitude_utm     486308.476715
 dtype: float64,
 array([[4540596.36230133, -872761.05464593],
        [-872761.05464593, 3492468.5075601 ]]))

In [19]:
# or instead is possible to perform a cross validation  
# with both glob_bw and alpha hyperparamters

In [20]:
grid_search_2D_VKDE = GridSearchCV(GaussianKDE(diag_cov=False),
                                                        {'glob_bw': global_bw_ranges,
                                                        'alpha':[None, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]},
                                                      cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_2d].dropna())

In [21]:
VKDE_2D = GaussianKDE(alpha=grid_search_2D_VKDE.best_params_['alpha'], 
                      glob_bw=grid_search_2D_VKDE.best_params_['glob_bw'])
VKDE_2D.fit(dataset[kde_columns_utm_2d])

(start_longitude_utm    121281.052258
 start_latitude_utm     486308.476715
 dtype: float64,
 array([[4540596.36230133, -872761.05464593],
        [-872761.05464593, 3492468.5075601 ]]))

In [22]:
#################################################
#the same can be replicated in four dimensions
#################################################

In [23]:
grid_search_4D_VKDE_alpha05 = GridSearchCV(GaussianKDE(diag_cov=False, alpha=0.5),
                                                        {'glob_bw': global_bw_ranges},
                                                      cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_4d].dropna())

/opt/anaconda3/envs/bigdatalab_cpu_202101/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: RuntimeWarning: invalid value encountered in subtract
  array_means[:, np.newaxis]) ** 2,


In [24]:
VKDE_4D_alpha05 = GaussianKDE(alpha=0.5, 
                              glob_bw=grid_search_4D_VKDE_alpha05.best_params_['glob_bw'])
VKDE_4D_alpha05.fit(dataset[kde_columns_utm_4d])

(start_longitude_utm    121281.052258
 start_latitude_utm     486308.476715
 end_longitude_utm      121662.870993
 end_latitude_utm       486031.891736
 dtype: float64,
 array([[ 4540596.36230133,  -872761.05464593,  1311966.98279999,
          -318824.6028541 ],
        [ -872761.05464593,  3492468.5075601 ,   -99281.00392884,
           417370.99847462],
        [ 1311966.98279999,   -99281.00392884,  8993501.90711864,
         -1445818.94580842],
        [ -318824.6028541 ,   417370.99847462, -1445818.94580842,
          5379351.57503014]]))

In [25]:
grid_search_4D_VKDE = GridSearchCV(GaussianKDE(diag_cov=False),
                                                        {'glob_bw': global_bw_ranges,
                                                        'alpha':[None, 0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]},
                                                      cv=10, n_jobs=-1).fit(dataset[kde_columns_utm_4d].dropna())

/opt/anaconda3/envs/bigdatalab_cpu_202101/lib/python3.7/site-packages/sklearn/model_selection/_search.py:814: RuntimeWarning: invalid value encountered in subtract
  array_means[:, np.newaxis]) ** 2,


In [26]:
VKDE_4D = GaussianKDE(alpha=grid_search_4D_VKDE.best_params_['alpha'], 
                      glob_bw=grid_search_4D_VKDE.best_params_['glob_bw'])
VKDE_4D.fit(dataset[kde_columns_utm_4d])

(start_longitude_utm    121281.052258
 start_latitude_utm     486308.476715
 end_longitude_utm      121662.870993
 end_latitude_utm       486031.891736
 dtype: float64,
 array([[ 4540596.36230133,  -872761.05464593,  1311966.98279999,
          -318824.6028541 ],
        [ -872761.05464593,  3492468.5075601 ,   -99281.00392884,
           417370.99847462],
        [ 1311966.98279999,   -99281.00392884,  8993501.90711864,
         -1445818.94580842],
        [ -318824.6028541 ,   417370.99847462, -1445818.94580842,
          5379351.57503014]]))

In [27]:
################################################################################
# THE FOLLOWIONG CELLS CONTAIN THE INSTRUCTIONS TO SAMPLE THE DIFFERENT 2D KDES,
# IN ORDER TO PRODUCE THE CONTOUR PLOTS IN THE OTHER NOTEBOOK NAMED "Amsterdam_plots.ipynb"
# FOR DOING THIS, THE SAMPLES ARE SAVED IN .pickle FILES AND MADE AVAILABLE DO BE UPLOADED
# AND PLOTTED

In [28]:
# perimeter city points in longitude and latitude
min_long = 115503.976
max_long = 129771.255
min_lat = 478827.935
max_lat = 492001.720

#building a grid of point for sampling the resulting KDEs
xx_utm = np.linspace(min_long, max_long, 1000)
yy_utm = np.linspace(min_lat, max_lat, 1000)
xg_utm, yg_utm = np.meshgrid(xx_utm,yy_utm)
grid_coords_utm = np.c_[xg_utm.ravel(), yg_utm.ravel()]

In [29]:
samples_fixedKDE_2D = np.exp(fixedKDE_2D.score_samples(grid_coords_utm)).reshape(*xg_utm.shape)

In [30]:
pickle.dump(samples_fixedKDE_2D, open('samples_fixed_kde', 'wb'))

In [31]:
samples_VKDE_2D_alpha05 = VKDE_2D_alpha05.predict(grid_coords_utm).reshape(*xg_utm.shape)

In [32]:
pickle.dump(samples_VKDE_2D_alpha05, open('samples_VKDE_2D_alpha05', 'wb'))

In [33]:
samples_VKDE_2D = VKDE_2D.predict(grid_coords_utm).reshape(*xg_utm.shape)

In [34]:
pickle.dump(samples_VKDE_2D, open('samples_VKDE_2D', 'wb'))

In [35]:
# FOR VKDE WITH ALPHA=0.5 WE CALCULATE ALSO THE INCREMENT/DECREMENT OF THE LOCAL BANDWIDTH
# WITH RESPECT TO THE GLOBAL BANDWIDTH

In [36]:
scatter_df = deepcopy(dataset)
scatter_df = scatter_df[['start_longitude_utm', 'start_latitude_utm']]
glob_bw = VKDE_2D_alpha05._glob_bw
loc_bws = (1/VKDE_2D_alpha05._inv_loc_bw)*glob_bw
scatter_df.loc[:,'loc_bw'] = loc_bws
scatter_df.loc[:,'inc_dec_perc'] = ((loc_bws-glob_bw)*100)/glob_bw
pd.to_pickle(scatter_df, './scatterplot_df')

NameError: name 'dataset_copy' is not defined